"""
Docker Agent Scaffolder — creates Ceagent v2 YAML + Docker files for
single-agent and multi-agent systems.

Ceagent is Docker's declarative AI agent runtime (YAML-driven, Go binary).
Reference: https://dev.to/docker/building-autonomous-ai-agents-with-docker-how-to-scale-intelligence-3oi

Single agent  → ceagent.yaml (root only) + Dockerfile + docker-compose.yml
Multi-agent   → ceagent.yaml (root + sub_agents) + Dockerfile + docker-compose.yml

Both outputs land in  agents/<agent_id>/  alongside any existing Python scaffold.
"""

import json
import textwrap
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional

AGENTS_DIR = Path(__file__).parent / "agents"

# ── Reserved ports — never auto-assign these ────────────────────────────────
_RESERVED_PORTS = {
    3000, 3001, 5737, 6333, 6379, 6380, 8000, 8001, 8002,
    8080, 8081, 8088, 8100, 8191, 8501, 8888, 9000, 9090,
    11434, 11435, 12434,
}

# Port pools: single agents start at 8301, multi-agent stacks at 8401
_SINGLE_PORT_START = 8301
_MULTI_PORT_START = 8401


def _safe_port(preferred: int, pool_start: int) -> int:
    """Return preferred port if free, otherwise next available from pool_start."""
    if preferred not in _RESERVED_PORTS:
        return preferred
    port = pool_start
    while port in _RESERVED_PORTS:
        port += 1
    return port


# ── Ceagent YAML helpers ─────────────────────────────────────────────────────

def _toolset_block(toolsets: List[Dict[str, Any]], indent: int = 6) -> str:
    """Render a toolsets: YAML list at the given indent level."""
    pad = " " * indent
    lines: List[str] = []
    for ts in toolsets:
        ts_type = ts.get("type", "builtin")
        if ts_type == "builtin":
            lines.append(f"{pad}- type: builtin\n{pad}  name: {ts['name']}")
        elif ts_type == "mcp":
            ref = ts.get("reference", "")
            lines.append(f"{pad}- type: mcp\n{pad}  reference: \"{ref}\"")
    if not lines:
        lines.append(f"{pad}- type: builtin\n{pad}  name: thinking")
    return "\n".join(lines)


def _ceagent_single_yaml(spec: Dict[str, Any]) -> str:
    """Render Ceagent v2 YAML for a single-root-agent configuration."""
    model = spec.get("model", "dmr/ai/gemma3")
    instruction = spec.get("instruction", "You are a helpful AI assistant.")
    toolsets = spec.get("toolsets", [{"type": "builtin", "name": "thinking"}])
    agent_id = spec.get("agent_id", "agent")
    date_str = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    # Build line-by-line to avoid textwrap.dedent stripping multi-line f-string variables.
    lines = [
        'version: "2"',
        f'# Single-agent Ceagent configuration',
        f'# Generated by Meta-Agent Builder — {date_str}',
        '#',
        f'# Run locally:  ceagent run ceagent.yaml',
        '# Run in Docker: docker compose up',
        f'# Push to Hub:  ceagent push <dockerhub-user>/{agent_id}',
        '',
        'agents:',
        '  root:',
        f'    model: {model}',
        '    instruction: |',
    ]
    for instr_line in instruction.strip().splitlines():
        lines.append(f'      {instr_line}')
    lines.append('    toolsets:')
    lines.append(_toolset_block(toolsets, indent=6))
    lines.append('')
    return '\n'.join(lines)


def _ceagent_multi_yaml(spec: Dict[str, Any]) -> str:
    """Render Ceagent v2 YAML for a multi-agent orchestration configuration."""
    root = spec.get("root_agent", {})
    sub_agents: List[Dict[str, Any]] = spec.get("sub_agents", [])
    agent_id = spec.get("agent_id", "multi_agent_stack")
    date_str = datetime.now(timezone.utc).strftime('%Y-%m-%d')

    root_model = root.get("model", "dmr/ai/gemma3")
    root_instruction = root.get("instruction", "You are an orchestrator. Delegate tasks to sub-agents.")
    root_toolsets = root.get("toolsets", [{"type": "builtin", "name": "thinking"}])

    sub_agent_ids = [sa.get("agent_id", f"sub_agent_{i}") for i, sa in enumerate(sub_agents)]

    # Build line-by-line to avoid textwrap.dedent stripping multi-line f-string variables.
    lines = [
        'version: "2"',
        '# Multi-agent Ceagent configuration',
        f'# Generated by Meta-Agent Builder — {date_str}',
        '#',
        '# The root agent orchestrates sub-agents via tool calls.',
        '# Run locally:  ceagent run ceagent.yaml',
        '# Run in Docker: docker compose up',
        f'# Push to Hub:  ceagent push <dockerhub-user>/{agent_id}',
        '',
        'agents:',
        '  root:',
        f'    model: {root_model}',
        '    instruction: |',
    ]
    for instr_line in root_instruction.strip().splitlines():
        lines.append(f'      {instr_line}')
    if sub_agent_ids:
        lines.append('    sub_agents:')
        for sid in sub_agent_ids:
            lines.append(f'      - {sid}')
    lines.append('    toolsets:')
    lines.append(_toolset_block(root_toolsets, indent=6))

    # Each sub-agent block
    for sa in sub_agents:
        sa_id = sa.get("agent_id", "sub_agent")
        sa_model = sa.get("model", "dmr/ai/gemma3")
        sa_desc = sa.get("description", f"Specialized {sa_id} sub-agent")
        sa_instruction = sa.get("instruction", f"You are a specialized {sa_id} agent.")
        sa_toolsets = sa.get("toolsets", [{"type": "builtin", "name": "thinking"}])

        lines.append('')
        lines.append(f'  {sa_id}:')
        lines.append(f'    model: {sa_model}')
        lines.append(f'    description: "{sa_desc}"')
        lines.append('    instruction: |')
        for instr_line in sa_instruction.strip().splitlines():
            lines.append(f'      {instr_line}')
        lines.append('    toolsets:')
        lines.append(_toolset_block(sa_toolsets, indent=6))

    lines.append('')
    return '\n'.join(lines)


# ── Shared file generators ───────────────────────────────────────────────────

def _dockerfile(agent_id: str) -> str:
    """Dockerfile that installs ceagent binary and runs the YAML config."""
    return textwrap.dedent(f"""\
        # Ceagent Docker image for: {agent_id}
        # Installs the Docker Ceagent runtime and runs ceagent.yaml
        FROM alpine:3.20 AS downloader

        ARG TARGETARCH=amd64
        RUN apk add --no-cache curl ca-certificates && \\
            ARCH=$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/') && \\
            curl -fsSL \\
              "https://github.com/docker/ceagent/releases/latest/download/ceagent-linux-${{ARCH}}" \\
              -o /usr/local/bin/ceagent && \\
            chmod +x /usr/local/bin/ceagent

        FROM alpine:3.20
        RUN apk add --no-cache ca-certificates
        COPY --from=downloader /usr/local/bin/ceagent /usr/local/bin/ceagent

        WORKDIR /agent
        COPY ceagent.yaml .

        # Docker Model Runner URL — override at runtime if needed
        ENV DOCKER_MODEL_RUNNER_URL=http://model-runner:12434

        ENTRYPOINT ["ceagent", "run"]
        CMD ["ceagent.yaml"]
    """)


def _env_example(providers: List[str]) -> str:
    """Generate .env.example with relevant provider keys."""
    lines = [
        "# Environment variables for this Ceagent agent stack",
        "# Copy to .env and fill in your values",
        "",
        "# Docker Model Runner (used for local DMR models)",
        "DOCKER_MODEL_RUNNER_URL=http://host-gateway:12434",
        "",
    ]
    if "openai" in providers:
        lines += ["# OpenAI", "OPENAI_API_KEY=sk-...", ""]
    if "anthropic" in providers:
        lines += ["# Anthropic", "ANTHROPIC_API_KEY=sk-ant-...", ""]
    if "gemini" in providers or "google" in providers:
        lines += ["# Google Gemini", "GEMINI_API_KEY=...", ""]
    if "groq" in providers:
        lines += ["# Groq", "GROQ_API_KEY=gsk_...", ""]
    return "\n".join(lines)


def _detect_providers(models: List[str]) -> List[str]:
    """Infer which providers are needed based on model strings."""
    providers = []
    for m in models:
        m_lower = m.lower()
        if m_lower.startswith("openai/") or "gpt" in m_lower:
            providers.append("openai")
        elif m_lower.startswith("anthropic/") or "claude" in m_lower:
            providers.append("anthropic")
        elif m_lower.startswith("gemini/") or "gemini" in m_lower:
            providers.append("gemini")
        elif m_lower.startswith("groq/"):
            providers.append("groq")
        # dmr/* models use Docker Model Runner — no API key needed
    return list(dict.fromkeys(providers))  # dedupe, preserve order


def _compose_single(agent_id: str, port: int, models: List[str]) -> str:
    """docker-compose.yml for a single-agent Ceagent stack."""
    needs_dmr = any(m.startswith("dmr/") for m in models)
    providers = _detect_providers(models)
    env_vars = "\n".join(f"      - {k}=${{{{  {k}:-  }}}}" for k in [
        "OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GEMINI_API_KEY", "GROQ_API_KEY",
    ] if k.replace("_API_KEY", "").lower() in providers)

    dmr_service = ""
    dmr_depends = ""
    if needs_dmr:
        dmr_service = textwrap.dedent(f"""\
          model-runner:
            image: docker/model-runner:0.1
            ports:
              - "12434:12434"
            restart: unless-stopped

        """)
        dmr_depends = textwrap.dedent("""\
            depends_on:
              model-runner:
                condition: service_started
        """)

    return textwrap.dedent(f"""\
        version: '3.9'
        # docker compose up -d
        services:
        {dmr_service}  {agent_id}:
            build: .
            image: ceagent/{agent_id}:latest
            {dmr_depends.strip()}
            ports:
              - "{port}:12000"
            environment:
              - DOCKER_MODEL_RUNNER_URL=http://model-runner:12434
        {env_vars}
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
            restart: unless-stopped

        networks:
          default:
            name: {agent_id}_network
    """)


def _compose_multi(agent_id: str, port: int, sub_agent_ids: List[str], models: List[str]) -> str:
    """docker-compose.yml for a multi-agent Ceagent stack."""
    needs_dmr = any(m.startswith("dmr/") for m in models)
    providers = _detect_providers(models)

    dmr_service = ""
    dmr_depends = ""
    if needs_dmr:
        dmr_service = textwrap.dedent("""\
          model-runner:
            image: docker/model-runner:0.1
            ports:
              - "12434:12434"
            restart: unless-stopped

        """)
        dmr_depends = "      depends_on:\n        - model-runner\n"

    env_section = ""
    for k in ["OPENAI_API_KEY", "ANTHROPIC_API_KEY", "GEMINI_API_KEY", "GROQ_API_KEY"]:
        if k.replace("_API_KEY", "").lower() in providers:
            env_section += f"        - {k}=${{{k}:-}}\n"

    return textwrap.dedent(f"""\
        version: '3.9'
        # Multi-agent Ceagent stack: root orchestrator + {len(sub_agent_ids)} sub-agent(s)
        # docker compose up -d
        services:
        {dmr_service}  {agent_id}:
            build: .
            image: ceagent/{agent_id}:latest
        {dmr_depends}    ports:
              - "{port}:12000"
            environment:
              - DOCKER_MODEL_RUNNER_URL=http://model-runner:12434
        {env_section.rstrip()}
            volumes:
              - /var/run/docker.sock:/var/run/docker.sock
            restart: unless-stopped

        networks:
          default:
            name: {agent_id}_network
    """)


def _readme_single(agent_id: str, spec: Dict[str, Any], port: int) -> str:
    model = spec.get("model", "dmr/ai/gemma3")
    instruction_preview = spec.get("instruction", "")[:120].strip()
    return textwrap.dedent(f"""\
        # {agent_id} — Single Docker Agent

        Auto-generated by **Meta-Agent Builder** using the Ceagent v2 runtime.

        ## Architecture

        ```
        ┌─────────────────────────────────────────┐
        │          docker compose stack           │
        │                                         │
        │  ┌─────────────────┐  ┌──────────────┐ │
        │  │  ceagent        │  │ model-runner │ │
        │  │  ({agent_id})   │→ │  (DMR:12434) │ │
        │  └─────────────────┘  └──────────────┘ │
        └─────────────────────────────────────────┘
        ```

        ## Model
        `{model}`

        ## Agent Purpose
        {instruction_preview}...

        ## Quick Start

        ### Option A — Local ceagent binary
        ```bash
        # Install ceagent (Go binary)
        curl -fsSL https://github.com/docker/ceagent/releases/latest/download/ceagent-linux-amd64 \\
          -o /usr/local/bin/ceagent && chmod +x /usr/local/bin/ceagent

        ceagent run ceagent.yaml
        ```

        ### Option B — Docker Compose (recommended)
        ```bash
        cp .env.example .env   # add your API keys if using external models
        docker compose up -d
        ```
        Agent available at: http://localhost:{port}

        ### Option C — Push & Share via Docker Hub
        ```bash
        ceagent push <your-dockerhub-user>/{agent_id}
        # Anyone can now run:
        ceagent run <your-dockerhub-user>/{agent_id}
        ```

        ## Files
        | File | Purpose |
        |------|---------|
        | `ceagent.yaml` | Ceagent v2 agent definition |
        | `Dockerfile` | Container that runs ceagent |
        | `docker-compose.yml` | Full stack with model runner |
        | `.env.example` | API key template |

        ## Toolsets Available
        - `thinking` — reasoning whiteboard for complex tasks
        - `shell` — execute shell commands
        - `filesystem` — read/write files
        - `todo` — shared task list for multi-step reasoning
        - `mcp` — Model Context Protocol servers (GitHub, Slack, etc.)
    """)


def _readme_multi(agent_id: str, spec: Dict[str, Any], port: int) -> str:
    root = spec.get("root_agent", {})
    sub_agents = spec.get("sub_agents", [])
    root_model = root.get("model", "dmr/ai/gemma3")

    agent_table = "| Agent | Model | Description |\n|-------|-------|-------------|\n"
    agent_table += f"| root (orchestrator) | `{root_model}` | Routes tasks to sub-agents |\n"
    for sa in sub_agents:
        agent_table += f"| {sa.get('agent_id', 'sub')} | `{sa.get('model', 'dmr/ai/gemma3')}` | {sa.get('description', '—')} |\n"

    return textwrap.dedent(f"""\
        # {agent_id} — Multi-Agent Docker Stack

        Auto-generated by **Meta-Agent Builder** using the Ceagent v2 runtime.

        ## Architecture

        ```
        ┌────────────────────────────────────────────────────────┐
        │                  docker compose stack                  │
        │                                                        │
        │  ┌─────────────────────────────────────────────────┐  │
        │  │              ceagent runtime                    │  │
        │  │                                                 │  │
        │  │  ┌──────────────┐    tool calls                │  │
        │  │  │ root agent   │ ──────────────────────────── │  │
        │  │  │ (orchestrate)│          │         │         │  │
        │  │  └──────────────┘          ▼         ▼         │  │
        {"│  │                      " + "  ".join([f"[{sa.get('agent_id','sub')}]" for sa in sub_agents[:3]])}  │  │
        │  └─────────────────────────────────────────────────┘  │
        │                                                        │
        │  ┌───────────────────┐                                 │
        │  │  model-runner     │  (local inference, free)        │
        │  │  port 12434       │                                 │
        │  └───────────────────┘                                 │
        └────────────────────────────────────────────────────────┘
        ```

        ## Agent Roster
        {agent_table}

        ## Quick Start

        ### Option A — Local ceagent binary
        ```bash
        ceagent run ceagent.yaml
        ```

        ### Option B — Docker Compose (recommended)
        ```bash
        cp .env.example .env
        docker compose up -d
        ```
        Stack available at: http://localhost:{port}

        ### Option C — Push & Share
        ```bash
        ceagent push <your-dockerhub-user>/{agent_id}
        ```

        ## Sub-Agent Communication
        Ceagent handles sub-agent delegation automatically via tool calls.
        When the root agent needs specialized help, it calls the appropriate
        sub-agent as if it were a function — no orchestration code required.

        ## Files
        | File | Purpose |
        |------|---------|
        | `ceagent.yaml` | Full multi-agent Ceagent v2 definition |
        | `Dockerfile` | Single container running the entire stack |
        | `docker-compose.yml` | Stack with model runner |
        | `.env.example` | API key template |
    """)


def _agent_meta(agent_id: str, scaffold_type: str, spec: Dict[str, Any]) -> Dict[str, Any]:
    """Generate agent.json compatible with list_scaffolded_agents()."""
    root_model = spec.get("model") or spec.get("root_agent", {}).get("model", "dmr/ai/gemma3")
    sub_agents = spec.get("sub_agents", [])
    return {
        "agent_id": agent_id,
        "agent_type": spec.get("agent_type", "docker_ceagent"),
        "domain": spec.get("domain", ""),
        "scaffold_type": scaffold_type,  # "single_docker" | "multi_docker"
        "runtime": "ceagent",
        "model": root_model,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "sub_agents": [sa.get("agent_id") for sa in sub_agents],
        "analysis_summary": {
            "complexity_level": spec.get("complexity_level"),
            "interaction_type": spec.get("interaction_type"),
            "problem_type": spec.get("problem_type"),
            "autonomy_level": spec.get("autonomy_level"),
        },
    }


# ── Public API ───────────────────────────────────────────────────────────────

def create_single_docker_agent(spec: Dict[str, Any]) -> Dict[str, Any]:
    """
    Scaffold a complete single-agent Ceagent v2 Docker project.

    spec keys:
      agent_id    : str   — folder name and image slug
      model       : str   — e.g. "dmr/ai/gemma3", "openai/gpt-4o"
      instruction : str   — agent system prompt / instruction
      toolsets    : list  — list of {"type":"builtin","name":"thinking"} dicts
      port        : int   — host port (defaults to next free port from 8301)
      domain      : str   — optional domain label
      complexity_level, interaction_type, autonomy_level, problem_type : optional

    Returns: {agent_id, path, files_created, ceagent_yaml, port}
    """
    agent_id = spec.get("agent_id", "agent")
    port = _safe_port(spec.get("port", _SINGLE_PORT_START), _SINGLE_PORT_START)
    model = spec.get("model", "dmr/ai/gemma3")

    agent_dir = AGENTS_DIR / agent_id
    agent_dir.mkdir(parents=True, exist_ok=True)

    ceagent_yaml = _ceagent_single_yaml(spec)
    files: List[str] = []

    def _write(name: str, content: str) -> None:
        (agent_dir / name).write_text(content)
        files.append(str(agent_dir / name))

    _write("ceagent.yaml", ceagent_yaml)
    _write("Dockerfile", _dockerfile(agent_id))
    _write("docker-compose.yml", _compose_single(agent_id, port, [model]))
    _write(".env.example", _env_example(_detect_providers([model])))
    _write("README.md", _readme_single(agent_id, spec, port))
    _write("agent.json", json.dumps(_agent_meta(agent_id, "single_docker", spec), indent=2) + "\n")

    return {
        "agent_id": agent_id,
        "path": str(agent_dir),
        "files_created": files,
        "ceagent_yaml": ceagent_yaml,
        "port": port,
        "scaffold_type": "single_docker",
        "runtime": "ceagent",
    }


def create_multi_docker_agent(spec: Dict[str, Any]) -> Dict[str, Any]:
    """
    Scaffold a multi-agent Ceagent v2 Docker project (root + sub-agents).

    spec keys:
      agent_id    : str   — folder name and image slug for the stack
      root_agent  : dict  — {model, instruction, toolsets}
      sub_agents  : list  — [{agent_id, model, instruction, description, toolsets}, ...]
      port        : int   — host port (defaults to next free from 8401)
      domain, complexity_level, etc. — optional labels

    Returns: {agent_id, path, files_created, ceagent_yaml, port, sub_agents}
    """
    agent_id = spec.get("agent_id", "multi_agent_stack")
    port = _safe_port(spec.get("port", _MULTI_PORT_START), _MULTI_PORT_START)

    root = spec.get("root_agent", {})
    sub_agents: List[Dict[str, Any]] = spec.get("sub_agents", [])

    all_models = [root.get("model", "dmr/ai/gemma3")]
    for sa in sub_agents:
        all_models.append(sa.get("model", "dmr/ai/gemma3"))

    sub_ids = [sa.get("agent_id", f"sub_{i}") for i, sa in enumerate(sub_agents)]

    agent_dir = AGENTS_DIR / agent_id
    agent_dir.mkdir(parents=True, exist_ok=True)

    ceagent_yaml = _ceagent_multi_yaml(spec)
    files: List[str] = []

    def _write(name: str, content: str) -> None:
        (agent_dir / name).write_text(content)
        files.append(str(agent_dir / name))

    _write("ceagent.yaml", ceagent_yaml)
    _write("Dockerfile", _dockerfile(agent_id))
    _write("docker-compose.yml", _compose_multi(agent_id, port, sub_ids, all_models))
    _write(".env.example", _env_example(_detect_providers(all_models)))
    _write("README.md", _readme_multi(agent_id, spec, port))
    _write("agent.json", json.dumps(_agent_meta(agent_id, "multi_docker", spec), indent=2) + "\n")

    return {
        "agent_id": agent_id,
        "path": str(agent_dir),
        "files_created": files,
        "ceagent_yaml": ceagent_yaml,
        "port": port,
        "scaffold_type": "multi_docker",
        "runtime": "ceagent",
        "sub_agents": sub_ids,
    }
